project_id = "gvoxndztrrpwhddvfhrr"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.voice-token]
verify_jwt = true

[functions.spotify-auth]
verify_jwt = true

[functions.search-user]
verify_jwt = true

[functions.send-board-invitation]
verify_jwt = true

[functions.send-admin-report]
verify_jwt = false

[functions.youtube-search]
verify_jwt = true

[functions.ai-chat]
verify_jwt = false